[versions]
gradle-publish = "1.1.0"
kotlin = "1.9.22"
amazon-bom = "2.20.18"
google-cloud-storage = "2.30.1"
s3-mock = "2.11.0"
retrofit = "2.9.0"
gson = "2.10.1"
protobuf = "3.25.1"

[libraries]
kotlin-bom = { group = "org.jetbrains.kotlin", name = "kotlin-bom", version.ref = "kotlin" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk8", version.ref = "kotlin" }
amazon-bom = { group = "software.amazon.awssdk", name = "bom", version.ref = "amazon-bom" }
amazon-s3 = { group = "software.amazon.awssdk", name = "s3", version.ref = "amazon-bom" }
amazon-sso = { group = "software.amazon.awssdk", name = "sso", version.ref = "amazon-bom" }
amazon-sts = { group = "software.amazon.awssdk", name = "sts", version.ref = "amazon-bom" }
adobe-s3-mock = { group = "com.adobe.testing", name = "s3mock", version.ref = "s3-mock" }
google-cloud-storage = { group = "com.google.cloud", name = "google-cloud-storage", version.ref = "google-cloud-storage" }
google-gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
google-protobuf-java = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuf" }
retrofit-core = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
gradle-publish = { id = "com.gradle.plugin-publish", version.ref = "gradle-publish" }
